name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/cache@v2.1.6
      id: vcpkg-cache
      with:
        path: '**/vcpkg'
        key: ${{ runner.os }}-Vcpkg-${{ hashFiles('**/.dependencies') }}
        restore-keys: |
            ${{ runner.os }}-Vcpkg-
            ${{ runner.os }}-

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Codecov
      uses: codecov/codecov-action@v1.2.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        gcov_root_dir: ${{runner.workspace}}/build
        directory: ${{runner.workspace}}/build
        verbose: true
        fail_ci_if_error: false

