name: Build Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PRESET: x64-linux-release

jobs:
  build_client:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake --preset ${{env.PRESET}} #-DENABLE_TEST_COVERAGE=ON
      
    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build --preset ${{env.PRESET}}

#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Test
      working-directory: ${{github.workspace}}
      run: ctest --preset ${{env.PRESET}}
